name: softair_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  flutter_screenutil: ^5.9.3
  razorpay_flutter: ^1.4.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.1.0
  dotted_line: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
